server:
  port: 8082
  servlet:
    context-path: /seller

rpc:
  client:
    url: http://localhost:8081/manager/
    basePackage: com.cy.finance.api
spring:
  cache:
    type: hazelcast
#  activemq:
#      broker-url: tcp://10.5.16.14:61616
#      packages:
#        trust-all: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/finance-seller?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456a
    backup:
      url: jdbc:mysql://localhost:3306/finance-seller-backup?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456a
  jpa:
    show-sql: true