spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  datasource:
    url: jdbc:mysql://localhost:3306/finance-manager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456a
  jpa:
    show-sql: true
#  activemq:
#    broker-url: tcp://10.5.16.14:61616
  jms:
    pub-sub-domain: true
server:
  context-path: /manager
  port: 8081
swagger:
  groupName: manager
  basePackage: com.cy.finance.manager.controller