spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/finance-manager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456a
  jpa:
    show-sql: true
server:
  context-path: /manager
  port: 8081